name: Deploy to mod.io

on:
  release:
    types: [published]
        
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: {% raw %}${{ github.head_ref }}{% endraw %}
      
    - name: Update Info.json
      uses: jossef/action-set-json-field@v1
      with:
        file: ./{{cookiecutter.project_name}}/Info.json
        field: Version
        value: {% raw %}${{ github.event.release.tag_name }}{% endraw %}
        
    - name: Commit Info.json
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
        git switch -c main
        git commit -m "Bumping version number in Info.json" ./{{cookiecutter.project_name}}/Info.json
        git push --set-upstream origin main
        git tag --force {% raw %}${{ github.event.release.tag_name }}{% endraw %}
        git push origin {% raw %}${{ github.event.release.tag_name }}{% endraw %} --force
      
    - name: Restore NuGet packages
      working-directory: {% raw %}${{env.GITHUB_WORKSPACE}}{% endraw %}
      run: nuget restore {% raw %}${{env.SOLUTION_FILE_PATH}}{% endraw %}
      
    - name: MSBuild
      working-directory: {% raw %}${{env.GITHUB_WORKSPACE}}{% endraw %}
      shell: powershell
      run: msbuild /m /p:Configuration={% raw %}${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}{% endraw %}
    
    - name: Test
      working-directory: {% raw %}${{env.GITHUB_WORKSPACE}}{% endraw %}
      run: dotnet test --verbosity normal --settings coverlet.runsettings --logger:trx
        
    - name: Prepare Files for Zip
      run: |
        New-Item -Path "{{cookiecutter.project_name}}\bin\Release\" -name "{{cookiecutter.project_name}}" -ItemType "directory"
        Copy-Item "{{cookiecutter.project_name}}\bin\Release\{{cookiecutter.project_name}}.dll" -Destination "{{cookiecutter.project_name}}\bin\Release\{{cookiecutter.project_name}}\{{cookiecutter.project_name}}.dll"
        Copy-Item "{{cookiecutter.project_name}}\bin\Release\Info.json" "{{cookiecutter.project_name}}\bin\Release\{{cookiecutter.project_name}}\Info.json"
        
    - name: Create ZIP
      id: filename
      shell: pwsh
      run: |
        $tag = "{% raw %}${{ github.event.release.tag_name }}{% endraw %}".Replace('.', '-')
        $archiveName = "{{cookiecutter.project_name}}-${tag}.zip"
        Compress-Archive -Path {{cookiecutter.project_name}}/bin/Release/{{cookiecutter.project_name}} -DestinationPath ${archiveName} -CompressionLevel Optimal
        echo "ARCHIVE_NAME=${archiveName}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        
    - name: Upload {{cookiecutter.project_name}}.zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        file: {% raw %}${{ env.ARCHIVE_NAME }}{% endraw %}
        asset_name: {% raw %}${{ env.ARCHIVE_NAME }}{% endraw %}
        tag: {% raw %}${{ github.event.release.tag_name }}{% endraw %}
        
    - name: Update repository.json Version
      id: update-json
      uses: 898anil/github-actions-json-edit@v0.2
      with:
        file_path: ./repository.json
        field_path: Releases.0.Version
        field_value: {% raw %}${{ github.event.release.tag_name }}{% endraw %}
        
    - name: Update repository.json DownloadUrl
      id: update-json2
      uses: 898anil/github-actions-json-edit@v0.2
      with:
        file_path: {% raw %}${{ steps.update-json.outputs.out_file }}{% endraw %}
        field_path: Releases.0.DownloadUrl
        field_value: "https://github.com/{% raw %}${{ github.repository_owner }}{% endraw %}/{{cookiecutter.project_name}}/releases/download/{% raw %}${{ github.event.release.tag_name }}{% endraw %}/${{ env.ARCHIVE_NAME }}{% endraw %}"
        
    - name: Overwrite repository.json
      run: |
        Copy-Item "{% raw %}${{ steps.update-json2.outputs.out_file }}{% endraw %}" "repository.json"
    
    - name: Commit repository.json
      run: |
        git commit -m "Bumping version number and download url in repository.json" ./repository.json
        git push origin main
      
    #- uses: nickelc/upload-to-modio@v1.0.1
    #  with:
    #    token: {% raw %}${{ secrets.MODIO_TOKEN }}{% endraw %}
    #    game: 629 # skaterxl
    #    mod: 0 # xltemplatemod (look up mod here)
    #    path: {% raw %}${{ env.ARCHIVE_NAME }}{% endraw %}
    #    version: {% raw %}${{ github.event.release.tag_name }}{% endraw %}
    #    changelog: {% raw %}${{ github.event.release.body }}{% endraw %}
